<table>
    <tr>
        <td  style="background-color:#ffffff;"><a href="https://qsoftware.lu.lv/index.php/qworld/" target="_blank"><img src="..\images\qworld.jpg" width="70%" align="left"></a></td>
        <td style="background-color:#ffffff;" width="*"></td>
        <td  style="background-color:#ffffff;vertical-align:text-top;"><a href="https://qsoftware.lu.lv" target="_blank"><img src="..\images\logo.jpg" width="25%" align="right"></a></td>        
    </tr>
    <tr><td colspan="3" align="right" style="color:#777777;background-color:#ffffff;font-size:12px;">
        prepared by <a href="http://abu.lu.lv" target="_blank">Abuzer Yakaryilmaz</a>
    </td></tr>
    <tr><td colspan="3" align="right" style="color:#bbbbbb;background-color:#ffffff;font-size:11px;font-style:italic;">
        This cell contains some macros. If there is a problem with displaying mathematical formulas, please run this cell to load these macros.
    </td></tr>
</table>
$ \newcommand{\bra}[1]{\langle #1|} $
$ \newcommand{\ket}[1]{|#1\rangle} $
$ \newcommand{\braket}[2]{\langle #1|#2\rangle} $
$ \newcommand{\dot}[2]{ #1 \cdot #2} $
$ \newcommand{\biginner}[2]{\left\langle #1,#2\right\rangle} $
$ \newcommand{\mymatrix}[2]{\left( \begin{array}{#1} #2\end{array} \right)} $
$ \newcommand{\myvector}[1]{\mymatrix{c}{#1}} $
$ \newcommand{\myrvector}[1]{\mymatrix{r}{#1}} $
$ \newcommand{\mypar}[1]{\left( #1 \right)} $
$ \newcommand{\mybigpar}[1]{ \Big( #1 \Big)} $
$ \newcommand{\sqrttwo}{\frac{1}{\sqrt{2}}} $
$ \newcommand{\dsqrttwo}{\dfrac{1}{\sqrt{2}}} $
$ \newcommand{\onehalf}{\frac{1}{2}} $
$ \newcommand{\donehalf}{\dfrac{1}{2}} $
$ \newcommand{\hadamard}{ \mymatrix{rr}{ \sqrttwo & \sqrttwo \\ \sqrttwo & -\sqrttwo }} $
$ \newcommand{\vzero}{\myvector{1\\0}} $
$ \newcommand{\vone}{\myvector{0\\1}} $
$ \newcommand{\vhadamardzero}{\myvector{ \sqrttwo \\  \sqrttwo } } $
$ \newcommand{\vhadamardone}{ \myrvector{ \sqrttwo \\ -\sqrttwo } } $
$ \newcommand{\myarray}[2]{ \begin{array}{#1}#2\end{array}} $
$ \newcommand{\X}{ \mymatrix{cc}{0 & 1 \\ 1 & 0}  } $
$ \newcommand{\Z}{ \mymatrix{rr}{1 & 0 \\ 0 & -1}  } $
$ \newcommand{\Htwo}{ \mymatrix{rrrr}{ \frac{1}{2} & \frac{1}{2} & \frac{1}{2} & \frac{1}{2} \\ \frac{1}{2} & -\frac{1}{2} & \frac{1}{2} & -\frac{1}{2} \\ \frac{1}{2} & \frac{1}{2} & -\frac{1}{2} & -\frac{1}{2} \\ \frac{1}{2} & -\frac{1}{2} & -\frac{1}{2} & \frac{1}{2} } } $
$ \newcommand{\CNOT}{ \mymatrix{cccc}{1 & 0 & 0 & 0 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 0 & 1 \\ 0 & 0 & 1 & 0} } $
$ \newcommand{\norm}[1]{ \left\lVert #1 \right\rVert } $

<h2> Probabilistic Operators</h2>

Remember Asja's biased coins, and her coin-flipping protocol.

$
GameCoins = \begin{array}{c|cc} & \mathbf{Head} & \mathbf{Tail} \\ \hline \mathbf{Head} & 0.6 & 0.3\\  \mathbf{Tail} & 0.4 & 0.7  \end{array} \equiv \begin{array}{c|cc} & \mathbf{0} & \mathbf{1} \\ \hline \mathbf{0} & 0.6 & 0.3 \\  \mathbf{1} & 0.4 & 0.7  \end{array}
$

We trace Asja's outcomes after two coin flips.

<b> At the beginning: </b>

<i> Remember the protocol:
<ol> 
    <li> whenever she gets a head, she flips one euro; </li>
    <li> whenever she gets a tail, she flips one cent; and </li>
    <li> she starts with flipping one euro by assuming that she got head from nowhere </li>
</ol>
</i>

She starts in state 0: $ v_0 = \myvector{1 \\ 0} $.

State 0 represents Head and state 1 represents Tail.

<b>After first coin flip:</b>

$  \mypar{ 
        GameCoins = \begin{array}{c|cc} & \mathbf{Head} & \mathbf{Tail} \\ \hline \mathbf{Head} & 0.6 & 0.3\\  \mathbf{Tail} & 0.4 & 0.7  \end{array}
        }
    \mypar{
        CurrentState=\myvector{1 \\ 0}
    } $
    
Each entry of the new vector is calculated by a row and current state:

$
\myvector{  0.6 \cdot 1 \\ + \\ 0.3 \cdot 0 \\ \hline 0.4 \cdot 1 \\ + \\ 0.7 \cdot 0  }
=
\myvector{ 0.6 + 0 \\ 0.4 + 0 }
=
\myvector{0.6 \\ 0.4}.
$

<b>After second coin flip:</b>

$  \mypar{ 
        GameCoins = \begin{array}{c|cc} & \mathbf{Head} & \mathbf{Tail} \\ \hline \mathbf{Head} & 0.6 & 0.3\\  \mathbf{Tail} & 0.4 & 0.7  \end{array}
        }
    \mypar{
        CurrentState=\myvector{0.6 \\ 0.4}
    } $
    
Each entry of the new vector is calculated by a row and current state:

$
\myvector{  0.6 \cdot 0.6 \\ + \\ 0.3 \cdot 0.4 \\ \hline 0.4 \cdot 0.6 \\ + \\ 0.7 \cdot 0.4  }
=
\myvector{ 0.36 + 0.12 \\ 0.24 + 0.28 }
=
\myvector{0.48 \\ 0.52}.
$

<b>Coin-flipping protocol</b> of Asja is a <i>probabilistic operator</i>.

Similarly to any operator, depending on the current state, Asja's coin-flipping protocol determines the next state.

$$
    \myvector{1 \\ 0} \xrightarrow{\mbox{Asja's coin-flipping protocol}} \myvector{0.6 \\ 0.4}
    \xrightarrow{\mbox{Asja's coin-flipping protocol}}  \myvector{0.48 \\ 0.52}.
$$

<font color="blue"><b>A probabilistic operator evolves the system from a probabilistic state to a probabilistic state.</b></font>

Asja's coin-flipping protocol transforms $ \myvector{ 0.8 \\ 0.2 } $ to $ \myvector{ 0.54 \\ 0.46 } $.

When calculating the new state, we use the table $  GameCoins = \begin{array}{c|cc} & \mathbf{Head} & \mathbf{Tail} \\ \hline \mathbf{Head} & 0.6 & 0.3\\  \mathbf{Tail} & 0.4 & 0.7  \end{array} $ and the current state $ \myvector{ 0.8 \\ 0.2 } $:

$$
    \myvector{ \myarray{c}{0.6 \cdot 0.8 \\ + \\ 0.3 \cdot 0.2} \\ \hline \myarray{c}{0.4 \cdot 0.8 \\ + \\ 0.7 \cdot 0.2} } = \myvector{ \myarray{c}{0.48 + 0.06} \\ \myarray{c}{0.32 + 0.14}  } = \myvector{ 0.54 \\ 0.46 }.
$$

<h3> Probabilistic operator </h3>

A probabilistic operator can be represented as a square table or matrix.

The entries of a probabilistic operator represent the transition probabilities between the states.

Therefore, <b>each entry is nonnegative.</b>

Each column represent the transition probabilities from a state to all states. Therefore, <b>the summation of all entries in each column is 1</b>, i.e., probability 1 is distributed to all states. 

Any matrix satisfying these two properties is called a <b> stochastic matrix</b>.

A probabilistic operator is a stochastic matrix, and vice versa.

<i> Remark that the operator of any linear system is reprented as a matrix. </i>

<h3> Probabilistic evolution </h3>

A probabilistic state is a stochastic vector,  say $ v $.

A probabilistic operator is a stochastic matrix, say $ A $,

If probabilistic operator $ A $ is applied to probabilistic state $ v $, the new state, say $v'$, is calculated as 

$$  v' = A \cdot v. $$

<i> Remark that the evolution of linear system is represented by matrix-vector multiplication. </i>

If we represent $ GameCoins $ as a matrix: $ \mymatrix{cc}{ 0.6 & 0.3 \\ 0.4 & 0.7 } $, then the new probabilistic state is calculated as

$$
    \myvector{ 0.54 \\ 0.46 } = \mymatrix{cc}{ 0.6 & 0.3 \\ 0.4 & 0.7 } \myvector{ 0.8 \\ 0.2 }.
$$

<h3> Task 1 </h3>

The operator $ GameCoins = \mymatrix{cc}{ 0.6 & 0.3 \\ 0.4 & 0.7 } $ is applied to the probabilistic state $ \myvector{ 0.1 \\ 0.9 } $. 

Then, the new probabilistic state is

$$ \mymatrix{cc}{ 0.6 & 0.3 \\ 0.4 & 0.7 } \myvector{ 0.1 \\ 0.9 } = \myvector{ 0.33 \\ 0.67 } .$$

Please verify the correctness of matrix-vector multiplication.

<h3> Task 2 </h3>

We are given the following probabilistic operator: $ B =  \mymatrix{ccc}{ 0.4 & 0.6 & 0 \\ 0.2 & 0.1 & 0.7 \\ 0.4 & 0.3 & 0.3 } $.

What is the transition probability from the second state to third state?

What is the transition probability from the third state to first state?

What is the transition probability from the first state to second state?

<h3>Task 3</h3>

Randomly construct a $ (3 \times 3 ) $-dimensional probabilistic operator.

That is, randomly determine the entries of the matrix that represents a probabilistic operator.

In [1]:
# let's start with a zero matrix
A = [
    [0,0,0],
    [0,0,0],
    [0,0,0]
]

# we will randomly pick the entries and then make normalization for each column
# it will be easier to iteratively construct the columns
# you may notice that each column is a probabilistic state
from random import randrange

normalization_factor = [0,0,0] # the normalization factor of each column may be different

for j in range(3): # each column is iteratively constructed
    normalization_factor[j] = 0
    while normalization_factor[j]==0: # the normalization factor cannot be zero
        for i in range(3):
            A[i][j] = randrange(101) # pick a random value between 0 and 100
            normalization_factor[j] += A[i][j]

# let's print matrix A before the normalization
# the entries are between 0 and 100
print("matrix A before normalization:")
for i in range(3):
    print(A[i])


# let's normalize each column
for j in range(3):
    for i in range(3):
        A[i][j] /= normalization_factor[j]  # shorter form of A[i][j] = A[i][j] / normalization_factor[j]
        
# let's print matrix A after the normalization
print() # print an empty line
print("matrix A after normalization:")
for i in range(3):
    print(A[i]) 

print()
print("the column summations must be 1")

sum = [0,0,0]
for j in range(3):
    for i in range(3):
        sum[j] += A[i][j]

print(sum) 

matrix A before normalization:
[91, 44, 96]
[89, 6, 84]
[55, 92, 18]

matrix A after normalization:
[0.3872340425531915, 0.30985915492957744, 0.48484848484848486]
[0.37872340425531914, 0.04225352112676056, 0.42424242424242425]
[0.23404255319148937, 0.647887323943662, 0.09090909090909091]

the column summations must be 1
[1.0, 1.0, 1.0]


<a href="B15_Probabilistic_Operators_Solutions.ipynb#task3">click for our solution</a>

<h3> Task 4 </h3>

What is the new probabilistic state if the operator $ B =  \mymatrix{ccc}{ 0.4 & 0.6 & 0 \\ 0.2 & 0.1 & 0.7 \\ 0.4 & 0.3 & 0.3 } $ is applied to the state $ \myvector{ 0.1 \\ 0.3 \\ 0.6 } $.

Please find the result by using matrix-vector multiplication.

Please do not use any python library for matrix-vector multiplication. 

<i> The new probabilistic state should be $ \myvector{0.22 \\ 0.47 \\ 0.31} $. </i>

In [2]:
# operator B
B = [
    [0.4,0.6,0],
    [0.2,0.1,0.7],
    [0.4,0.3,0.3]
]

# the current state
v = [0.1,0.3,0.6]

newstate = []

index = 0

for row in B:
    newstate.append(0)
    for i in range(len(row)):
        newstate[index] = newstate[index] + row[i] * v[i]
    index = index + 1
    
print(newstate)

[0.22, 0.47, 0.31]


<a href="B15_Probabilistic_Operators_Solutions.ipynb#task4">click for our solution</a>

<h3> Task 5 </h3>

Write a function named <i>linear_evolve</i> that takes a probabilistic operator and a probabilistic state, and then returns the new probabilistic state.

Please do not use any python library for matrix-vector multiplication.

Your function should work for any dimension.

Save your function so that you can use it later.
<br><br>
<div style="background-color:#f8f8f8;">
<b><u>Write the content of a code cell</u></b> into an external file:
    
    %%writefile linear_evolve.py
This command should be placed in the first line of cell, and then the cell should be executed.
</div>

Test your function on $ B = \mymatrix{ccc}{ 0.4 & 0.6 & 0 \\ 0.2 & 0.1 & 0.7 \\ 0.4 & 0.3 & 0.3 } $ and $ \myvector{0.1 \\ 0.3 \\ 0.6} $. 

The new probabilistic state should be $ \myvector{0.22 \\ 0.47 \\ 0.31} $.

Then, evolve your system for 5, 10, 20, and 40 steps.

This system should evolve to a fixed probabilistic state.

Change your initial state to  $ \myvector{1 \\ 0 \\ 0} $, and see whether the converged state is the same or not.

In [9]:
%%writefile linear_evolve.py

UsageError: %%writefile is a cell magic, but the cell body is empty.


In [15]:
def linear_evolve(operator,state):
    newstate=[]
    for i in range(len(operator)): # for each row
        # we calculate the corresponding entry of the new state
        newstate.append(0) # we set this value to 0 for the initialization
        for j in range(len(state)): # for each element in state
            newstate[i] = newstate[i] + operator[i][j] * state[j] # summation of pairwise multiplications
    return newstate # return the new probabilistic state
# test the function

# operator for the test
B = [
    [0.4,0.6,0],
    [0.2,0.1,0.7],
    [0.4,0.3,0.3]
]

# state for test
v = [0.1,0.3,0.6]

newstate = linear_evolve(B,v)
print(newstate)

for step in [5,10,20,40]:
    new_state = [0.1,0.3,0.6] # initial state
    for i in range(step):
        new_state = linear_evolve(B,new_state)
    print(new_state)


[0.22, 0.47, 0.31]
[0.33378399999999997, 0.33309199999999994, 0.333124]
[0.3333328297599999, 0.3333337260799999, 0.33333344415999994]
[0.33333333333309395, 0.3333333333336499, 0.3333333333332556]
[0.33333333333333315, 0.33333333333333315, 0.33333333333333315]


In [16]:
    
# change the initial state

for step in [5,10,20,40]:
    new_state = [1,0,0] # initial state
    for i in range(step):
        new_state = linear_evolve(B,new_state)
    print(new_state)

[0.33255999999999997, 0.33391999999999994, 0.33352]
[0.33333399039999995, 0.3333327007999999, 0.33333330879999995]
[0.3333333333334263, 0.33333333333305704, 0.3333333333335162]
[0.33333333333333315, 0.33333333333333315, 0.33333333333333315]


<a href="B15_Probabilistic_Operators_Solutions.ipynb#task4">click for our solution</a>

<h3> Task 6 [extra] </h3>

The operator $ \widetilde{I} = \mymatrix{cc}{0.999 & 0.001\\ 0.001 & 0.999 } $ is very similar to Identity operator. However, it converges to a certain matrix.

Find $  \underbrace{\widetilde{I} \cdot \widetilde{I} \cdots \widetilde{I}}_{k\mbox{ times}} $ for $ k = 10, 100, 1000, 10000, 100000 $ and then guess the converging matrix.

In [22]:
import numpy as np 
i = np.array([[0.999, 0.001],
             [0.001, 0.999]], float)

I = np.array([[0.999, 0.001],
             [0.001,0.999]], float)


for k in [10,100,1000,10000,100000]:
    print(k)
    for _ in range(1, k):
        I = I.dot(i)
    print(I)

10
[[0.99008952 0.00991048]
 [0.00991048 0.99008952]]
100
[[0.90197496 0.09802504]
 [0.09802504 0.90197496]]
1000
[[0.55440136 0.44559864]
 [0.44559864 0.55440136]]
10000
[[0.5 0.5]
 [0.5 0.5]]
100000
[[0.5 0.5]
 [0.5 0.5]]


<h3> Task 7 [extra] </h3>

Repeat Task 6 for the operator $ \widetilde{NOT} = \mymatrix{cc}{0.001 & 0.999\\ 0.999 & 0.001 } $.

In [23]:
import numpy as np 
i = np.array([[0.001, 0.999],
             [0.999, 0.001]], float)

I = np.array([[0.001, 0.999],
             [0.999, 0.001]], float)



for k in [10,100,1000,10000,100000]:
    print(k)
    for _ in range(1, k):
        I = I.dot(i)
    print(I)

10
[[0.99008952 0.00991048]
 [0.00991048 0.99008952]]
100
[[0.09802504 0.90197496]
 [0.90197496 0.09802504]]
1000
[[0.55440136 0.44559864]
 [0.44559864 0.55440136]]
10000
[[0.5 0.5]
 [0.5 0.5]]
100000
[[0.5 0.5]
 [0.5 0.5]]
